#!/usr/bin/env python3
"""Bundle Inkling into one self-contained HTML file.

Inlines the stylesheets, the scripts, and the woff2 faces as data URIs, so the
result is a single file that opens from disk and needs no network at all.

    python3 build.py                  -> dist/inkling.html   (whole document)
    python3 build.py --fragment PATH  -> body content only, for hosts that
                                         supply their own document skeleton
"""

import argparse
import base64
import hashlib
import pathlib
import re

ROOT = pathlib.Path(__file__).parent
SRC = ROOT / 'index.html'


def font_data_uri(match, css_dir):
    """Rewrite url("../fonts/x.woff2") to a base64 data: URI."""
    url = match.group(1).strip('\'"')
    if url.startswith('data:'):
        return match.group(0)
    raw = (css_dir / url).resolve().read_bytes()
    return 'url("data:font/woff2;base64,%s")' % base64.b64encode(raw).decode()


def read_css(path):
    css = path.read_text(encoding='utf-8')
    return re.sub(r'url\((["\'][^)]+["\'])\)',
                  lambda m: font_data_uri(m, path.parent), css)


def build():
    html = SRC.read_text(encoding='utf-8')

    def inline_css(match):
        href = match.group(1)
        return '<style>\n%s\n</style>' % read_css(ROOT / href)

    def inline_js(match):
        src = match.group(1)
        return '<script>\n%s\n</script>' % (ROOT / src).read_text(encoding='utf-8')

    def inline_icon(match):
        path = ROOT / match.group(1)
        data = base64.b64encode(path.read_bytes()).decode()
        return '<link rel="apple-touch-icon" href="data:image/png;base64,%s">' % data

    html = re.sub(r'<link rel="stylesheet" href="([^"]+)">', inline_css, html)
    html = re.sub(r'<script src="([^"]+)"></script>', inline_js, html)
    html = re.sub(r'<link rel="apple-touch-icon" href="([^"]+)">', inline_icon, html)
    # A lone file has nowhere to serve a manifest from, and the icons it names
    # are separate requests — drop the link rather than ship a broken one.
    html = re.sub(r'\s*<link rel="manifest" href="[^"]+">', '', html)
    return html


def fragment(html):
    """Strip the document skeleton, keeping the title, the styles that were
    inlined into <head>, and everything in <body>."""
    head = re.search(r'<head>(.*?)</head>', html, re.S)
    body = re.search(r'<body>(.*)</body>', html, re.S)
    title = re.search(r'<title>(.*?)</title>', html, re.S)

    parts = []
    if title:
        parts.append('<title>%s</title>' % title.group(1))
    if head:
        parts += re.findall(r'<style>.*?</style>', head.group(1), re.S)
    parts.append(body.group(1).strip() if body else html)
    return '\n'.join(parts) + '\n'


# Everything the app needs to run with no network. Order does not matter;
# the service worker fetches them all before it considers itself installed.
PRECACHE = [
    './',
    'index.html',
    'manifest.webmanifest',
    'assets/css/tokens.css',
    'assets/css/app.css',
    'assets/js/events.js',
    'assets/js/app.js',
    'assets/fonts/caprasimo-latin.woff2',
    'assets/fonts/caprasimo-latin-ext.woff2',
    'assets/fonts/figtree-latin.woff2',
    'assets/fonts/figtree-latin-ext.woff2',
    'assets/icons/apple-touch-icon.png',
    'assets/icons/icon-192.png',
    'assets/icons/icon-512.png',
    'assets/icons/icon-maskable-512.png',
]

GEN_START = '/* --- generated by build.py, do not edit --- */'
GEN_END = '/* --- end generated --- */'


def write_sw():
    """Stamp the worker with a version that changes whenever the app does.

    A browser only installs a new worker if sw.js differs byte for byte, so
    the version has to be derived from the content it caches — otherwise a
    deploy ships new files that no installed client ever asks for.
    """
    sw_path = ROOT / 'sw.js'
    source = sw_path.read_text(encoding='utf-8')

    digest = hashlib.sha256()
    for name in PRECACHE:
        if name == './':
            continue
        digest.update((ROOT / name).read_bytes())
    # The worker's own logic counts too: a fix in here must reach clients
    # even when not one cached asset has changed.
    head, _, rest = source.partition(GEN_START)
    _, _, tail = rest.partition(GEN_END)
    digest.update((head + tail).encode('utf-8'))
    version = digest.hexdigest()[:12]

    assets = ',\n  '.join("'%s'" % a for a in PRECACHE)
    block = "%s\nconst VERSION = '%s';\nconst ASSETS = [\n  %s\n];\n%s" % (
        GEN_START, version, assets, GEN_END)
    sw_path.write_text(head + block + tail, encoding='utf-8')
    return version


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--fragment', metavar='PATH',
                    help='write body content only to PATH')
    args = ap.parse_args()

    if not args.fragment:
        print('sw.js  version %s' % write_sw())

    html = build()

    if args.fragment:
        out = pathlib.Path(args.fragment)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(fragment(html), encoding='utf-8')
    else:
        out = ROOT / 'dist' / 'inkling.html'
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(html, encoding='utf-8')

    print('%s  %.0f KB' % (out, out.stat().st_size / 1024))


if __name__ == '__main__':
    main()
