/* Inkling service worker.
 *
 * Two jobs: keep the whole app on the device so it opens with no network at
 * all, and let a new version replace the installed one in place — no
 * removing and re-adding the home-screen icon.
 *
 * The update dance is deliberate. A new worker installs in the background
 * and then *waits*: it does not take over the page that is already running,
 * because swapping the cache underneath a live page can pair new HTML with
 * scripts the old one already loaded. The page notices the waiting worker,
 * offers a reload, and only then does the worker take over.
 */

/* --- generated by build.py, do not edit --- */
const VERSION = '663055279d1e';
const ASSETS = [
  './',
  'index.html',
  'manifest.webmanifest',
  'assets/css/tokens.css',
  'assets/css/app.css',
  'assets/js/holidays.js',
  'assets/js/events.js',
  'assets/js/app.js',
  'assets/fonts/caprasimo-latin.woff2',
  'assets/fonts/caprasimo-latin-ext.woff2',
  'assets/fonts/figtree-latin.woff2',
  'assets/fonts/figtree-latin-ext.woff2',
  'assets/fonts/notosansthai.woff2',
  'assets/icons/apple-touch-icon.png',
  'assets/icons/icon-192.png',
  'assets/icons/icon-512.png',
  'assets/icons/icon-maskable-512.png'
];
/* --- end generated --- */

const CACHE = 'inkling-' + VERSION;
const SHELL = './';

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(
      // `reload` is load-bearing: a plain addAll is allowed to satisfy itself
      // from the HTTP cache, which happily hands back the very files this
      // update exists to replace. The cache name changes, the contents do
      // not, and the update silently does nothing.
      ASSETS.map((url) => new Request(url, { cache: 'reload' }))
    ))
  );
  // No skipWaiting here on purpose — see the note at the top.
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(
      keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))
    );
    await self.clients.claim();
  })());
});

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;

  let url;
  try { url = new URL(req.url); } catch (e) { return; }
  if (url.origin !== self.location.origin) return;

  // Every navigation resolves to the one page, so it opens offline whatever
  // path it was launched from.
  if (req.mode === 'navigate') {
    event.respondWith((async () => {
      const cached = await caches.match(SHELL);
      if (cached) return cached;
      return fetch(req);
    })());
    return;
  }

  event.respondWith((async () => {
    const cached = await caches.match(req);
    if (cached) return cached;
    const res = await fetch(req);
    // Anything the precache list missed still works on the next launch.
    if (res && res.ok && res.type === 'basic') {
      const cache = await caches.open(CACHE);
      cache.put(req, res.clone());
    }
    return res;
  })());
});
